{% set version = "1.0.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-faraway
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/faraway_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/faraway/faraway_{{ version }}.tar.gz
  sha256: 1074ed85a0cf018fc2fd3e2a48bed666b2fa06b8461b7a3820aeb67b34a52d5d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lme4
    - r-nlme
  run:
    - r-base
    - r-lme4
    - r-nlme

test:
  commands:
    - $R -e "library('faraway')"           # [not win]
    - "\"%R%\" -e \"library('faraway')\""  # [win]

about:
  home: http://people.bath.ac.uk/jjf23/
  license: GPL-2.0-or-later
  summary: Books are "Practical Regression and ANOVA in R" on CRAN, "Linear Models with R" published 1st Ed. August 2004, 2nd Ed. July 2014 by CRC press, ISBN 9781439887332, and "Extending the Linear Model with R" published by CRC press in 1st Ed. December 2005 and 2nd Ed. March 2016, ISBN 9781584884248.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
